amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.005 #0.005 #0.2
    alpha2: 0.005 #0.005 #0.2
    alpha3: 0.005 #0.005 #0.2
    alpha4: 0.005 #0.005 #0.2
    alpha5: 0.005 #0.005 #0.2
    base_frame_id: "base_link" #"base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 6.0 #2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 3000 #2000
    min_particles: 500 #500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0 #0.001
    recovery_alpha_slow: 0.0 #0.001
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.9 #0.5
    z_max: 0.05 #0.05
    z_rand: 0.5
    z_short: 0.05
    sigma_hit: 0.05 #0.2
    scan_topic: /scan
    map_topic: /map
    set_initial_pose: true #false
    always_reset_initial_pose: false
    first_map_only: false #true
    initial_pose:
      x: 0.0 
      y: 0.0
      z: 0.0 
      yaw: 0.0 

amcl_map_client:
  ros__parameters:
    use_sim_time: False

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: False

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: "/home/raspberry/map/office.yaml"

map_saver:
  ros__parameters:
    use_sim_time: False
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True